### ISSUE TITLE
Concurrent Connection/Request Handling

### ISSUE THREAD

**Issue by benjchristensen** [reactive-ipc/reactive-ipc-jvm#24] opened 2015-03-31 05:26 UTC
A server needs to receive connections (TCP etc) and requests (HTTP etc) concurrently. 

For example, on a 32-core machine where each core can be receiving IO connections and requests, each core should be able to process independently of each other. 

This means we can not represent a server handler as a `Publisher<Connection>` or `Publisher<Request>` since `Publisher` can not invoke `onNext` concurrently. 

If `Publisher` was used for this it would result in all CPU cores serializing through the single `Publisher`. 

Thus a server handler must just be a function call that is invoked concurrently whenever a connection or request is received.

**Comment by smaldini** [comment] 2015-03-31 11:53
Yeah the oNext argument is somehow interesting, one can argue that serializing the publishers in a non blocking pipeline could leave you manage how many in-flight/concurrent connections you can accept at most. But a Function<> would suit better probably :+1:

**Comment by rstoyanchev** [comment] 2015-04-13 14:06
Agreed.

This appears to be a duplicate of #7.

**Comment by NiteshKant** [comment] 2015-04-27 06:50
Closing this as we seem to agree that a server must not be represented as a `Publisher`

**Closed as completed by NiteshKant** 2015-04-27 06:50 UTC
